# -*- coding: utf-8 -*-
"""students performance week-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jG6Qwh3qXijOn08mXN52E9Qet_d1ynzj
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("/StudentsPerformance_preprocessed.csv")
df
df.head()

print(df.shape)
print(df.columns)
print(df.info())

sns.barplot(
    data=df,
    x='parental level of education',
    y='math score',
    hue='lunch'
)

plt.title('Math Score by Parental Education and Lunch Type')
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='math score'
)

plt.title('Math Score: Test Preparation vs No Preparation')
plt.xlabel('Test Preparation Course')
plt.ylabel('Math Score')

plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x='math score',
    y='writing score'
)

plt.title('Math Score vs Writing Score')
plt.xlabel('Math Score')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=df,
    x='reading score',
    y='writing score'
)

plt.title('Reading Score vs Writing Score')
plt.xlabel('Reading Score')
plt.ylabel('Writing Score')
plt.show()

correlation = df[
    ['math score', 'reading score', 'writing score']
].corr()

print(correlation)

plt.figure(figsize=(7,5))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    vmin=-1,
    vmax=1
)

plt.title('Correlation Between Student Scores')
plt.show()

print("Math-Reading Correlation:",
      df['math score'].corr(df['reading score']))

print("Math-Writing Correlation:",
      df['math score'].corr(df['writing score']))

print("Reading-Writing Correlation:",
      df['reading score'].corr(df['writing score']))