# -*- coding: utf-8 -*-
"""healthcare analise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAhncEtRHLMYYiwZtEar-iRdVR5wXBA5
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/healthcare_dataset.csv")
df

df.head()

df.info()

df.describe()

df.isnull().sum()

for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].fillna('not gather')

print("Missing values after filling:")
print(df.isnull().sum())

df['Admission_Date'] = pd.to_datetime(df['Admission_Date'])
df['Discharge_Date'] = pd.to_datetime(df['Discharge_Date'])

print(df['Admission_Date'].dtype)
print(df['Discharge_Date'].dtype)

df['Medical_Code'].isnull()

print(df['Admission_Type'].value_counts())

df['Admission_Type'] = df['Admission_Type'].str.lower()

df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
df['Hospital_Stay_Days'].describe()

df['Hospital_Stay_Days'] = (df['Discharge_Date'] - df['Admission_Date']).dt.days
print(df['Billing_Amount'].describe())
print(df['Hospital_Stay_Days'].describe())