# -*- coding: utf-8 -*-
"""Healthcare_data B

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xdfmYOkOX3o6LANWtVx72SjZduSZMJ8R
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/healthcare_dataset.csv")
df

df.head()

df.info()

billing = df.groupby(["Medical Condition","Insurance Provider"])["Billing Amount"].sum().unstack()
billing

billing.plot(
    kind = "bar",
    stacked = True,
    figsize = (10,6)
)

plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.show()

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])
df['Hospital_Stay_Days'] = (df['Discharge Date'] - df['Date of Admission']).dt.days
print(df['Billing Amount'].describe())
print(df['Hospital_Stay_Days'].describe())

df['Admission Month']=df['Date of Admission'].dt.to_period('M')
df['Admission Month']

monthly_admission = df.groupby('Admission Month').size()
monthly_admission

plt.figure(figsize=(12, 6))
monthly_admission.plot(kind="line", marker="o")

plt.title("Monthly Patient Admission")
plt.xlabel("Month")
plt.ylabel("Admission Count")
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

correlation_matrix = df['Date of Admission']
df['Date of Admission']

df['Date of Admission'] = pd.to_datetime(df['Date of Admission'])
df['Discharge Date'] = pd.to_datetime(df['Discharge Date'])

df['Stay Duration'] = (df['Discharge Date'] - df['Date of Admission']).dt.days

correlation_matrix = df[['Age', 'Stay Duration', 'Billing Amount']].corr()
correlation_matrix

sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()