# -*- coding: utf-8 -*-
"""shopify stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SnZPap07MEFQHyfI0xBwsoRCEdC6xD3v
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/shopify_stock.csv")

df.head()

df['date'] = pd.to_datetime(df['date'], utc=True)

plt.figure(figsize=(8, 5))
sns.lineplot(x='date', y='close', data=df)
plt.title('Shopify Closing Price Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.grid(True)
plt.show()

df['Daily_Return'] = df['close'].pct_change()

plt.figure(figsize=(6, 5))
sns.histplot(df['Daily_Return'].dropna(), bins=60, kde=True, color='darkred')
plt.title('Disply  Shopify Daily Returns')
plt.xlabel('Daily Return')
plt.ylabel('width')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 6))
sns.kdeplot(df['Daily_Return'].dropna(), fill=True, color='blue')
plt.title('KDE shopiy file')
plt.xlabel('Daily Return')
plt.ylabel('width')
plt.grid(True)
plt.show()